In [1]:
import numpy as np
import pandas as pd

In [2]:
a = [35, 5, 75, 10, 2]
data = pd.Series(a)

In [3]:
print(data)
data = pd.Series(a, index=['a','b','c','d','e'])
print(data)

0    35
1     5
2    75
3    10
4     2
dtype: int64
a    35
b     5
c    75
d    10
e     2
dtype: int64


In [4]:
data.values

array([35,  5, 75, 10,  2], dtype=int64)

In [5]:
data.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [6]:
data['c']

75

In [7]:
data[1:]

b     5
c    75
d    10
e     2
dtype: int64

In [8]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}
population = pd.Series(population_dict)

In [9]:
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [10]:
population['Texas':'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

In [11]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [12]:
area = pd.Series(area_dict)

In [13]:
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


In [14]:
states = pd.DataFrame({'population': population, 'area': area})

In [15]:
print(states)

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995


In [16]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [17]:
states.columns

Index(['population', 'area'], dtype='object')

In [18]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [19]:
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [20]:
pd.DataFrame(np.random.rand(3, 2),
columns=['Pop', 'Area'],
index=['a', 'b', 'c'])


Pop      Area
a  0.477729  0.232909
b  0.338555  0.238813
c  0.091364  0.000781

In [21]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [22]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [23]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [24]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [25]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])

In [26]:
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [27]:
'a' in data

True

In [28]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [29]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [30]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [31]:
data['e'] = 10.2

In [32]:
print(data)

a     0.25
b     0.50
c     0.75
d     1.00
e    10.20
dtype: float64


In [33]:
data['a':'b']

a    0.25
b    0.50
dtype: float64

In [34]:
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [35]:
data[( data > 0.30 ) & (data < 10.0)]

b    0.50
c    0.75
d    1.00
dtype: float64

In [36]:
data[['a', 'e']]

a     0.25
e    10.20
dtype: float64

In [37]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))

In [38]:
print(ser)

0    6
1    3
2    7
3    4
dtype: int32


In [39]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                         columns=['A', 'B', 'C', 'D'])

In [40]:
print(df)

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4


In [41]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [42]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [43]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                         'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                               'New York': 19651127}, name='population')

In [44]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [45]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [46]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [47]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                         columns=list('AB'))

In [48]:
print(A)

   A   B
0  1  11
1  5   1


In [49]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                         columns=list('BAC'))

In [50]:
print(B)

   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6


In [51]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [52]:
fill = A.stack().mean()
print(fill)

A.add(B, fill_value=fill)

4.5


A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [53]:
A = rng.randint(10, size=(3, 4))
print(A)

[[3 8 2 4]
 [2 6 4 8]
 [6 1 3 8]]


In [54]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]
print(df)

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8


In [55]:
for dtype in ['object', 'int']:           
    print("dtype =", dtype)           
    %timeit np.arange(1E6, dtype=dtype).sum()           
    print()

dtype = object
126 ms ± 1.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
5.6 ms ± 350 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

